name: cron-fork

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0,4,8,12,16,20 * * *'

jobs:
  generate:
    name: Generate on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    permissions:
      contents: write
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fork V2Ray Subscription
        run: |
          # mkdir
          mkdir -p dist/gh-pages
          # https://github.com/freefq/free
          curl -Lj https://raw.githubusercontent.com/freefq/free/master/v2 -o dist/gh-pages/freefq_free
          # https://github.com/Pawdroid/Free-servers
          curl -Lj https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub -o dist/gh-pages/pawdroid_free_servers
          # https://github.com/mfuu/v2ray
          curl -Lj https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray -o dist/gh-pages/mfuu_v2ray
          # https://github.com/aiboboxx/v2rayfree
          curl -Lj https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2 -o dist/gh-pages/aiboboxx_v2rayfree
      - name: Checkout Github Pages
        continue-on-error: true # 忽略 gh-pages 分支未创建
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Merge Github Pages
        run: |
          # 避免 gh-pages 分支未创建
          mkdir -p gh-pages
          #
          if [ -d dist/gh-pages ]; then cp -r dist/gh-pages/. gh-pages/; fi
      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages
          branch: gh-pages
